### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MontnDev** [WhoAmI1000/discord-oauth2-example#1]
Hi, I always get the error:
{ message: '401: Unauthorized', code: 0 }
if someone wants to authorize... 
Please help!

**Comment by rdcr0** [comment]
Hi Boostcounter,
Did you enter your client ID and client secret (lines 10 and 11, respectively) in oauth.js?

**Comment by rdcr0** [comment]
Closed due to inactivity. Please reopen your issue if this problem persists.
