### ISSUE TITLE
Invalid OAuth2 redirect_uri

### ISSUE THREAD

**Issue by johndoddsjr** [WhoAmI1000/discord-oauth2-example#4]
In the guide it says:
"Click "Add Redirect" then type http://localhost:7100/ into the box and save your changes."

Placing the / at the end causes an error while trying to authorize with discord. 
Removing the slash fixes the issue. 
http://localhost:7100

**Comment by rdcr0** [comment]
Hello johndoddsjr,

Thank you for your observation. I have corrected the text and will correct the image in the tutorial soon. Thanks for your input!
