### ISSUE TITLE
weird error (no /user)

### ISSUE THREAD

**Issue by LeoonThePaster** [WhoAmI1000/discord-oauth2-example#5]
hey, i get that output
![image](https://user-images.githubusercontent.com/84630142/160258564-94d81f67-e980-41cb-adb8-f9e035cad647.png)

please help me asap.

**Comment by rdcr0** [comment]
Hello oneBroke,

Is this being hosted locally or on a server? Either way, was there anything logged in the server console?

**Comment by LeoonThePaster** [comment]
hey, its hosted on an Server. and no nothing has printed in the console

**Comment by LeoonThePaster** [comment]
![image](https://user-images.githubusercontent.com/84630142/160258821-248f2a35-da00-4fbe-abb5-1a413dc9b99f.png)

**Comment by rdcr0** [comment]
In _oauth.js_, try adding a `console.log(response.data);` between lines 50 and 51. Try running the app again and take a look at what the console logs (does it display the correct discord info, or give an error/html page?). Could you also verify that express.js and node-fetch are up-to-date (or just directly update them with `npm up express node-fetch`)?

**Comment by LeoonThePaster** [comment]
hey, i tried that console.log but nothing logged to console... i needed to downgrade node-fetch because in newest version you cant use require().

**Comment by LeoonThePaster** [comment]
![image](https://user-images.githubusercontent.com/84630142/160259084-70b5cdb1-25de-4e65-97a2-55aad1b9015a.png)

**Comment by rdcr0** [comment]
You can load the latest version of node-fetch asynchronously by replacing line 7 (loading node-fetch) with
`const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));`.
See if that works; I’m currently not able to do much tinkering on my own device, but I should be able to tomorrow.

**Comment by LeoonThePaster** [comment]
okay let me try

**Comment by LeoonThePaster** [comment]
soooo... nothing changed after using that. ima try some other stuff rn if you have an fix pls send it to me fast.
good night if not heh

**Comment by rdcr0** [comment]
I’ll look into it and send you a fix as soon as I can. Good night to you, I guess.

**Comment by rdcr0** [comment]
Oh, real quick: Did this show before or after you logged in with discord and were redirected back?

**Comment by rdcr0** [comment]
Hey oneBroke, could you confirm whether this appeared before or after you logged in on the discord portal and redirected back to the page?

**Comment by rdcr0** [comment]
Hello oneBroke,

I will close this issue to to inactivity. This looks to be like an error with the /user POST API. Please reopen this if this issue persists.
