### ISSUE TITLE
Cannot GET /user

### ISSUE THREAD

**Issue by dinxsh** [WhoAmI1000/discord-oauth2-example#7]
please help me with this error 🐱

**Comment by rdcr0** [comment]
Hey dinxsh,
An error stating "Cannot GET /user" indicates that you are likely sending a GET request to /user. However, /user is for POST requests, not GET requests (see [this](https://github.com/WhoAmI1000/discord-oauth2-example/blob/3e1af2e65886ec12a63e0304143e4292243bda2c/oauth.js#L38). See the index.html file for information on how to make a proper request to /user.

I hope this helps!

**Comment by dinxsh** [comment]
MB it did work. thanks a bunch @WhoAmI1000
